GoldenIDC/urls.py
from django.conf.urls import url, include
from golden_web import urls
from GoldenIDC import views

urlpatterns = [
    url(r'^', include(urls, namespace='golden_web'))
]

handler403 = views.permission_denied
handler404 = views.page_no_found
handler500 = views.page_erro

golden_web/urls.py
from django.conf.urls import url
from golden_web import views
urlpatterns = [
    url(r'^$', view=views.index, name='index'),
    url(r'^dataCenter/$', view=views.data_center, name='data_center'),
    url(r'^show/(?P<dcname>\w+)/$', view=views.show_data, name='show_data'),
    url(r'^service/(?P<name>\w+)/$', view=views.service_system, name='service_system'),
    url(r'^resource/(?P<name>\w+)/$', view=views.resource, name='resource'),
    url(r'^corporation/$', view=views.corporation, name='corporation'),
    url(r'^baiduMap/$', view=views.baidu_map, name='baidumap'),
]

golden_web/models.py
from django.db import models

# Create your models here.

GoldenIDC/views.py
from django.shortcuts import render

def page_no_found(request):
    return render(request, 'erro.html', {'erro': 404, 'info': '别迷失了方向'}, status=404)


def page_erro(request):
    return render(request, 'erro.html', {'erro': 500, 'info': '服务器挂掉了'}, status=500)


def permission_denied(request):
    return render(request, 'erro.html', {'erro': 403, 'info': '服务器不能处理此请求'}, status=403)

golden_web/views.py
from django.shortcuts import render

# Create your views here.

# 主页
def index(request):
    return render(request, 'golden_web/index.html')

# 所有数据中心
def data_center(request):
    return render(request, 'golden_web/dataCenter.html')

# 数据中心详情
def show_data(request, dcname):
    return render(request, 'golden_web/datacenter/%s.html' % dcname)

# 服务体系
def service_system(request, name):
    return render(request, 'golden_web/fuwutixi/%s.html' % name)

# 资源方案
def resource(request, name):
    return render(request, 'golden_web/zyfa/%s.html' % name)

def corporation(request):
    return render(request, 'golden_web/corporation.html')

# 百度地图
def baidu_map(request):
    return render(request, 'baiduMap.html')

templates/base_site.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}
{% block style %}{% endblock style %}
{% block script %}{% endblock script %}

{% block body %}
    <header>
        <div class="header01">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="left">
                            <a href="/" class="logo">
                                <img src="{% static 'golden_web/img/goldenlogo.png' %}"/>
                            </a>
                        </div>
                        <div class="right">
                            <ul class="nav1">
                                <li>
                                    <a href="/">首页</a>
                                </li>
                                <li class="product">
                                    <a href="{% url 'golden_web:data_center' %}">数据中心</a>
                                </li>
                                <li>
                                    <a href="#">服务体系</a>
                                    <ul class="nav2 no-animates">
                                        <li><a href="{% url 'golden_web:service_system' "consult" %}">咨询服务</a></li>
                                        <li><a href="{% url 'golden_web:service_system' "kefu" %}">客服服务</a></li>
                                        <li><a href="{% url 'golden_web:service_system' "maintain" %}">运维服务</a></li>
                                        <li><a href="{% url 'golden_web:service_system' "customize" %}">定制服务</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">资源方案</a>
                                    <ul class="nav2 no-animates">
                                        <li><a href="{% url 'golden_web:resource' "trusteeship" %}">服务器托管</a></li>
                                        <li><a href="{% url 'golden_web:resource' "cabinet" %}">机柜资源</a></li>
                                        <li><a href="{% url 'golden_web:resource' "broadband" %}">大带宽资源</a></li>
                                        <li><a href="{% url 'golden_web:resource' "customization" %}">行业定制化</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="{% url 'golden_web:corporation' %}">关于我们</a>
                                </li>
                                <li>
                                    <a href="tencent://message/?uin=505569470&Site=www.goldenidc.com&Menu=yes">联系我们</a>
                                </li>
                                <li class="lang">
                                    <a href="/">中文</a>
                                    <a href="">EN</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header02">
            <div class="header_moblie">
                <div class="header_moblie">
                    <!--移动端头部-->
                    <div class="mobile">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-6">
                                    <a href="/" class="text-center logo">
                                        <img src="{% static 'golden_web/img/goldenlogo.png' %}"/>
                                    </a>
                                </div>
                                <div class="col-xs-6">
                                    <div class="right">
                                        <div href="###" class="navbar-btn">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mobile-nav">
                        <div class="close"></div>
                        <ul class="dropdown no-animates">
                            <li class="active"><a href="/">首页</a></li>
                            <li>
                                <a href="javascript:;">数据中心</a>
                                <ul class="nav2">
                                    <li><a href="{% url 'golden_web:show_data' "kglt" %}">天津空港联通数据中心</a></li>
                                    <li><a href="{% url 'golden_web:show_data' "hygjsjg" %}">天津华苑国际数据港</a></li>
                                    <li><a href="{% url 'golden_web:show_data' "kgyd" %}">天津空港移动数据中心</a></li>
                                    <li><a href="{% url 'golden_web:show_data' "dxtb" %}">天津电信天波数据中心</a></li>
                                    <li><a href="{% url 'golden_web:show_data' "yxf" %}">天津宜兴阜数据中心</a></li>
                                    <li><a href="{% url 'golden_web:show_data' "sxd" %}">天津绍兴道数据中心</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">服务体系</a>
                                <ul class="nav2">
                                    <li><a href="{% url 'golden_web:service_system' "consult" %}">咨询服务</a></li>
                                    <li><a href="{% url 'golden_web:service_system' "kefu" %}">客服服务</a></li>
                                    <li><a href="{% url 'golden_web:service_system' "maintain" %}">运维服务</a></li>
                                    <li><a href="{% url 'golden_web:service_system' "customize" %}">定制服务</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">资源方案</a>
                                <ul class="nav2">
                                    <li><a href="{% url 'golden_web:resource' "trusteeship" %}">服务器托管</a></li>
                                    <li><a href="{% url 'golden_web:resource' "cabinet" %}">机柜资源</a></li>
                                    <li><a href="{% url 'golden_web:resource' "broadband" %}">大带宽资源</a></li>
                                    <li><a href="{% url 'golden_web:resource' "customization" %}">行业定制化</a></li>
                                </ul>
                            </li>
                            <li>


                                <a href="{% url 'golden_web:corporation' %}">关于我们</a>
                            </li>
                            <li>
                                <a href="tencent://message/?uin=505569470&Site=www.goldenidc.com&Menu=yes">联系我们</a>
                            </li>
                        </ul>
                        <p class="lang right">
                            <a href="/" class="inline-block">中文</a>|
                            <a href="" class="inline-block">EN</a>
                        </p>
                    </div>
                    <div class="cd-overlay"></div>
                </div>
            </div>
        </div>
        <!--产品列表-->
        <div class="header03 no-animates">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <dl class="product_box">
                            <dt><a href="{% url 'golden_web:show_data' "kglt" %}" style="cursor: default;" class="tdn">天津联通空港数据中心</a>
                            </dt>
                            <dd><a class="tdn">4000个标准机架</a></dd>
                            <dd><a class="tdn">出口带宽可达400G</a></dd>
                            <dd><a class="tdn">总建筑面积70500平方米</a></dd>
                            <dd><a class="tdn">直连国家骨干网核心设备</a></dd>
                            <dd><a class="tdn">7*24小时驻场运维</a></dd>
                        </dl>
                        <dl class="product_box">
                            <dt><a href="{% url 'golden_web:show_data' "hygjsjg" %}" style="cursor: default;"
                                   class="tdn">天津华苑国际数据港</a></dt>
                            <dd><a class="tdn">五星级高端IDC机房</a></dd>
                            <dd><a class="tdn">20910平方米独立大楼</a></dd>
                            <dd><a class="tdn">2000kva大型柴油发电机</a></dd>
                            <dd><a class="tdn">自动消防系统</a></dd>
                            <dd><a class="tdn">八级抗震</a></dd>
                            <dd><a class="tdn">7*24小时驻场运维</a></dd>


                        </dl>
                        <dl class="product_box">
                            <dt><a href="{% url 'golden_web:show_data' "kgyd" %}" style="cursor: default;" class="tdn">天津空港移动数据中心</a>
                            </dt>
                            <dd><a class="tdn">总建筑面积约8000平米</a></dd>
                            <dd><a class="tdn">移动互联网应用总部</a></dd>
                            <dd><a class="tdn">华为模块化建设</a></dd>
                            <dd><a class="tdn">恒温恒湿空调系统</a></dd>
                            <dd><span class="tdn">7*24小时驻场运维</span></dd>

                        </dl>
                        <dl class="product_box">
                            <dt><a href="{% url 'golden_web:show_data' "dxtb" %}" style="cursor: default;" class="tdn">天津电信天波数据中心</a>
                            </dt>
                            <dd><a class="tdn">电信级的机房场地</a></dd>
                            <dd><a class="tdn">高速稳定的网络保障</a></dd>
                            <dd><a class="tdn">充足持续的电力保障</a></dd>
                            <dd><a class="tdn">严密的安全保障</a></dd>
                            <dd><a class="tdn">可靠的消防保障</a></dd>
                            <dd><span class="tdn">7*24小时驻场运维</span></dd>

                        </dl>
                        <dl class="product_box">
                            <dt><a href="{% url 'golden_web:show_data' "yxf" %}" style="cursor: default;" class="tdn">天津宜兴埠数据中心</a>
                            </dt>
                            <dd><a class="tdn">四星级IDC机房</a></dd>
                            <dd><a class="tdn">多线BGP</a></dd>
                            <dd><a class="tdn">联通、电信、移动、教育</a></dd>
                            <dd><a class="tdn">2套800KVA UPS供电</a></dd>
                            <dd><span class="tdn">7*24小时驻场运维</span></dd>


                        </dl>
                        <dl class="product_box">
                            <dt><a href="{% url 'golden_web:show_data' "sxd" %}" style="cursor: default;" class="tdn">天津绍兴道数据中心</a>
                            </dt>
                            <dd><a class="tdn">北京骨干网出口</a></dd>
                            <dd><a class="tdn">10 级的抗震强度</a></dd>
                            <dd><a class="tdn">UPS 双路电源系统</a></dd>
                            <dd><a class="tdn">梅蓝日蓝大型立式空调</a></dd>
                            <dd><a class="tdn">采用防火构架材料</a></dd>
                            <dd><a class="tdn">UPS不间断电源</a></dd>
                            <dd><a class="tdn">7*24小时驻场运维</a></dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block body2 %}{% endblock body2 %}
    {% block foo %}
        <script>
            if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))) {
                new WOW().init();
            }
            ;
        </script>
        <a href="http://mqu.cn/" style="position:fixed;display: none;">mqu.cn</a>
        <a href="http://site.nuo.cn/" style="position:fixed;display: none;">site.nuo.cn</a>
        <footer>
            <div class="footer01">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-3"><img
                                src="{% static 'golden_web/img/foot_icon1.png' %}"><span>秒级快速响应</span></div>
                        <div class="col-xs-3"><img src="{% static 'golden_web/img/foot_icon2.png' %}"><span>7×24×365 全天候服务</span>
                        </div>
                        <div class="col-xs-3"><img
                                src="{% static 'golden_web/img/foot_icon3.png' %}"><span>VVIP 大客户服务</span></div>
                        <div class="col-xs-3"><img
                                src="{% static 'golden_web/img/foot_icon4.png' %}"><span>高标准云计算数据中心</span></div>
                    </div>
                </div>
            </div>
            <div class="footer02" >
                <p class="copyright center">IDC、ISP经营许可证编号： 津B1.B2-20150037 ©Copyright 天津金石创世网络科技有限公司</p>
                <div class="container">
                    <div class="row">
{#                        <div class="col-xs-12">#}
{#                            <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=000000000000"#}
{#                               target="_blank" class="beian right"><em class="sprite"></em> 公安备案号：粤公网安备 000000000000号</a>#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </footer>
        <script type="text/javascript">
            $('#owl-banner').owlCarousel({
                items: 1,
                autoplay: true,
                loop: true,
                dots: true
            });
        </script>
    {% endblock foo %}
{% endblock body %}

templates/golden_web/corporation.html
{% extends 'base_site.html' %}
{% load static %}
{% block title %}金石创世网络科技有限公司-关于我们{% endblock title %}
{% block body2 %}
    <div class="relative clearfix">
        <div class="banner">
            <img src="{% static 'golden_web/img/corporation.jpg' %}"/>
        </div>
        <div class="breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12" style="font-size:0;">
                        <a class="cur" href="{% url 'golden_web:corporation' %}">公司简介</a></div>
                </div>
            </div>
        </div>
    </div>

    <div class="page_about">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="num">
                        <h2>
                            金石创世
                        </h2>
                        <ul>
                            <li>
                                <strong>20+</strong>
                                <p>
                                    资源节点
                                </p>
                            </li>
                            <li>
                                <strong style="line-height: 66px; font-family:;" 微软雅黑";font-size:30px;font-weight:normal;"="">6座</strong>
                                <p>
                                    核心机房
                                </p>
                            </li>
                            <li>
                                <strong>2000G+</strong>
                                <p>
                                    网络宽带
                                </p>
                            </li>
                            <li>
                                <strong>6000R+</strong>
                                <p>
                                    机柜储配
                                </p>
                            </li>
                            <li>
                                <strong>2B+</strong>
                                <p>
                                    IP储备
                                </p>
                            </li>
                            <li>
                                <strong>160+</strong>
                                <p>
                                    服务客户
                                </p>
                            </li>
                        </ul>
                        <p style="text-align:center;font-size:16px;">
                            金石创世成立于2014年6月，是全球具有重要影响力的网络空间基础设施服务提供商，
                            也是中国领先的第三方独立数据中心运营商。作为中国卓越的互联互通网络平台。
                            金石创世致力于提供业界领先的数据中心服务、中立的云服务、中立的混合IT服务和领先的CDN服务，打造具有核心技术、超大规模运营能力的网络空间基础设施运营平台。
                            高能数据中心，依托在数据中心建设、网络连接等方面的经验势，将数据中心从高品质时代引入高能时代。
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="concept" style="background: #f5f5f5;padding: 70px 0 60px;">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 style="margin-bottom: 30px;">金石创世</h2>

                        <p align="center">
                            <span style="font-size:18px;">开心&nbsp;&nbsp;&nbsp; 尊重&nbsp;&nbsp;&nbsp; 拼搏&nbsp;&nbsp;&nbsp; 负责&nbsp;&nbsp;&nbsp; 感恩</span>
                        </p>
                        <br>
                        <br>

                        <div class="col-xs-5">
                            <p><img src="{% static 'golden_web/img/goldenlogo.png' %}" alt=""></p>
                            <br>
                            <br>
                            <br>
                            <p style="font: bold 16px/16px 'Mcr">地址：北京海淀区清华东路甲1号凯时广场5楼B612</p>
                            <br>
                            <br>
                            <p>邮编：100083</p>
                            <p>电话：18601057002</p>
                            <p>QQ：505569470</p>
                            <br>
                            <br>
                            <p>市场合作:18601057002</p>
                            <br>
                            <p>合作邮箱：qiuguokui@goldenidc.com</p>
                            <br>
                            <br>
                            <p><span style="font-size: 40px; color: red">7*24*365为您服务</span></p>
                        </div>
                        <div class="col-xs-7">
                            <iframe src="{% url 'golden_web:baidumap' %}" frameborder="0" scrolling="no" style="width: 100%; height: 496px"></iframe>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body2 %}

templates/golden_web/dataCenter.html
{% extends 'base_site.html' %}
{% load static %}
{% block title %}IDC机房，IDC托管，IDC数据中心，服务器租赁，金石创世网络科技有限公司{% endblock title %}
{% block body2 %}
    <div class="relative clearfix">
        <div class="banner">
            <img src="{% static 'golden_web/img/datacenter-bg.jpg' %}"/>
        </div>
    </div>
    <div class="product_list">
        <div class="container">
            <div class="row animated bounceInUp">
                <h1 class="center catname" style="font-size: 38px;margin-bottom: 20px;">数据中心</h1>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="box center">
                        <div class="img-responsive">
                            <img src="{% static 'golden_web/img/datecenter/tjkg-x.jpg' %}"/>
                        </div>
                        <div class="info">
                            <div class="h100">
                                <div class="table">
                                    <a class="table-cell">
                                        <div class="txt">
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "kglt" %}" >4000个标准机架</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "kglt" %}" >出口带宽可达400G</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "kglt" %}" >建筑面积70500平方米</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "kglt" %}" >直连国家骨干网核心设备</a>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h1 class="center catname">天津联通空港数据中心</h1>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="box center">
                        <div class="img-responsive">
                            <img src="{% static 'golden_web/img/datecenter/hygjsjg-x.jpg' %}"/>
                        </div>
                        <div class="info">
                            <div class="h100">
                                <div class="table">
                                    <div class="table-cell">
                                        <div class="txt">
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "hygjsjg" %}" >五星级高端IDC机房</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "hygjsjg" %}" >20910平方米独立大楼</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "hygjsjg" %}" >2000kva大型柴油发电机</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "hygjsjg" %}" >八级抗震</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <h1 class="center catname">天津华苑国际数据港</h1>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="box center">
                        <div class="img-responsive">
                            <img src="{% static 'golden_web/img/datecenter/kdyd-x.jpg' %}"/>
                        </div>
                        <div class="info">
                            <div class="h100">
                                <div class="table">
                                    <div class="table-cell">
                                        <div class="txt">
                                            <a class="arrow-right-b tdn"  href="{% url 'golden_web:show_data' "kgyd" %}">建筑面积约8000平米</a>
                                            <a class="arrow-right-b tdn"  href="{% url 'golden_web:show_data' "kgyd" %}">移动互联网应用总部</a>
                                            <a class="arrow-right-b tdn"  href="{% url 'golden_web:show_data' "kgyd" %}">华为模块化建设</a>
                                            <a class="arrow-right-b tdn"  href="{% url 'golden_web:show_data' "kgyd" %}">恒温恒湿空调系统</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <h1 class="center catname">天津空港移动数据中心</h1>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="box center">
                        <div class="img-responsive">
                            <img src="{% static 'golden_web/img/datecenter/dxtb-x.jpg' %}"/>
                        </div>
                        <div class="info">
                            <div class="h100">
                                <div class="table">
                                    <div class="table-cell">
                                        <div class="txt">
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "dxtb" %}">高速稳定的网络保障</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "dxtb" %}">充足持续的电力保障</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "dxtb" %}">严密的安全保障</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "dxtb" %}">可靠的消防保障</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <h1 class="center catname">天津电信天波数据中心</h1>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="box center">
                        <div class="img-responsive">
                            <img src="{% static 'golden_web/img/datecenter/yxf-x.jpg' %}"/>
                        </div>
                        <div class="info">
                            <div class="h100">
                                <div class="table">
                                    <div class="table-cell">
                                        <div class="txt">
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "yxf" %}">四星级IDC机房</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "yxf" %}">多线BGP</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "yxf" %}">联通、电信、移动、教育</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "yxf" %}">2套800KVA UPS供电</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <h1 class="center catname">天津宜兴阜数据中心</h1>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="box center">
                        <div class="img-responsive">
                            <img src="{% static 'golden_web/img/datecenter/sxd-d.jpg' %}"/>
                        </div>
                        <div class="info">
                            <div class="h100">
                                <div class="table">
                                    <div class="table-cell">
                                        <div class="txt">
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "sxd" %}">北京骨干网出口</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "sxd" %}">10 级的抗震强度</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "sxd" %}">梅蓝日蓝大型立式空调</a>
                                            <a class="arrow-right-b tdn" href="{% url 'golden_web:show_data' "sxd" %}">兰州电信新区枢纽IDCC</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <h1 class="center catname">天津绍兴道数据中心</h1>
                </div>
            </div>
        </div>
    </div>
    <style type="text/css">
        .breadcrumb {
            display: none;
        }
    </style>

{% endblock body2 %}

templates/golden_web/datacenter/yxf.html
{% extends 'golden_web/datacenter/dc_base.html' %}
{% load static %}
{% block title %}天津宜兴阜数据中心{% endblock title %}

{% block dataname %}天津宜兴阜数据中心{% endblock dataname %}
{% block dc_menu %}
    <a href="{% url 'golden_web:show_data' "kglt" %}">天津空港联通数据中心</a>
    <a href="{% url 'golden_web:show_data' "hygjsjg" %}">天津华苑国际数据港</a>
    <a href="{% url 'golden_web:show_data' "kgyd" %}">天津空港移动数据中心</a>
    <a href="{% url 'golden_web:show_data' "dxtb" %}">天津电信天波数据中心</a>
    <a class="cur" href="{% url 'golden_web:show_data' "yxf" %}">天津宜兴阜数据中心</a>
    <a href="{% url 'golden_web:show_data' "sxd" %}">天津绍兴道数据中心</a>
{% endblock dc_menu %}

{% block dc_img %}
    <img src="{% static 'golden_web/img/datecenter/yxf-d.jpg' %}"/>
{% endblock dc_img %}

{% block dc_info %}
    <div class="information">
        <h1 class="name">{% block dc_info_name %}天津宜兴阜数据中心{% endblock dc_info_name %}</h1>
        <ul class="tab_list clearfix">
            <li class="cur">机房概况</li>
            <li>地理位置</li>
            <li>电力系统</li>
            <li>空调系统</li>
            <li>消防设施</li>
            <li>网络资源</li>
            <li>机柜规格</li>
        </ul>
        <ul class="tab_content clearfix">
            <li>
                •	产权单位：中国联通 <br>
                •	设计机架数：1000个 <br>
                •	开通时间：2014年
                •	机房面积：1000平方米
                •	抗震等级：8
                该机房目前通过20Gbps高速光纤通道连接绍兴道数据中心，建筑面积达1000余平方米。

            </li>
            <li>
                <p>宜兴埠机房坐落于天津市北辰区新宜白大道天津联通宜兴埠局院内，距京津塘高速公路宜兴阜出口1.2公里，交通便利。</p>
            </li>
            <li>
                <p>宜兴埠机房设有高低压变配电间，引入2路市电，现有卡特比勒400KW柴油发电机组一台，作为后备支撑电源,新增6台400KVA UPS主机设备，并联组成两套(2+1)冗余并联系统，2套800KVA UPS供电系统分别为3层，4层IDC机房供电。</p>
            </li>
            <li>
                <p>每层IDC机房内布置十台6万大卡/时机房专用精密空调。采用下送风方式空调系统，即在机柜近侧布置活动地板送风口将冷风送到机柜的送风方式。</p>
            </li>
            <li>
                <p></p>
            </li>
            <li>
                <p>~宜兴埠机房3层和4层共用Cisco7609交换机为核心设备。由两台核心设备互为备份，确保网络的安全性和稳定性。机房出口带宽为20G。</p>
                <p>~多线BGP（联通、电信、移动、教育、铁通）、单线（电信）、单线（联通）</p>
            </li>
            <li></li>
        </ul>

        {#                        <a href="" download class="download btn noradius colorDodge">下载机房信息</a>#}

    </div>
{% endblock dc_info %}